import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "cecess",
  description: "Generated by create next app",
};

import { UserProvider } from "@/features/auth/hooks/use-user";
import { LanguageProvider } from "@/features/i18n/context/language-context";
import { CookieConsent } from "@/features/public/components/cookie-consent";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <UserProvider>
          <LanguageProvider>
            {children}
            <CookieConsent />
          </LanguageProvider>
        </UserProvider>
      </body>
    </html>
  );
}
